esphome:
  name: epaper-panel
  friendly_name: ePaper Panel

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5i4azvXNTvFw31YkZK22aQnOsbzA51b5+PvZBq8T9M8="

ota:
  - platform: esphome
    password: "84622fc91e2dce7290ce38cc33e68251"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Epaper-Panel Fallback Hotspot"
    password: "OZrb7lk6llkP"

captive_portal:
    
http_request:
  verify_ssl: false
  timeout: 10s
  watchdog_timeout: 15s

online_image:
  - id: dashboard_image
    format: BMP
    type: BINARY
    buffer_size: 16000
    url: http://192.168.1.188:10000/lovelace/epaper-display?viewport=800x480&format=bmp&eink=2&invert #change this link to your screenshot link
    update_interval: 2min
    on_download_finished:
      - delay: 0ms
      - component.update: main_display

spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

display:
  - platform: waveshare_epaper
    id: main_display
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin: 
      number: GPIO4
      inverted: true
    reset_pin: GPIO2
    model: 7.50inv2
    update_interval: never
    lambda: |-
      it.image(0, 0, id(dashboard_image));
